/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 courageHouse.glb 
*/
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";
import { React, useEffect, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./Model/courageHouse.glb");
  //groundtexture
  const groundtexture = useLoader(TextureLoader, "./Textures/ground.jpg");
  const sofatexture = useLoader(TextureLoader, "./Textures/sofa.jpg");
  const chimneytexture = useLoader(TextureLoader, "./Textures/chimney.jpg");
  const couragetexture = useLoader(TextureLoader, "./Textures/courage.jpeg");
 

  couragetexture.center.set(0.5, 0.5);
  couragetexture.repeat.set(1, 1); 
  couragetexture.wrapS = THREE.ClampToEdgeWrapping;
  couragetexture.wrapT = THREE.ClampToEdgeWrapping; 
  couragetexture.rotation = Math.PI;
  groundtexture.wrapS = groundtexture.wrapT = THREE.RepeatWrapping;
  groundtexture.repeat.set(10, 10);
  groundtexture.rotation = Math.PI / 4;
  groundtexture.center.set(0.5, 0.5);
  //groundtexture
  const cupboardtexture = useLoader(TextureLoader, "./Textures/cupboard.jpg");
  //skills

  const blenderTexture = useLoader(
    TextureLoader,
    "./Textures/skills/blender.png"
  );
  const figmaTexture = useLoader(TextureLoader, "./Textures/skills/figma.png");
  const flutterTexture = useLoader(
    TextureLoader,
    "./Textures/skills/flutter.png"
  );
  const javaTexture = useLoader(TextureLoader, "./Textures/skills/java.png");
  const javascriptTexture = useLoader(
    TextureLoader,
    "./Textures/skills/javascript.png"
  );
  const linuxTexture = useLoader(TextureLoader, "./Textures/skills/linux.png");

  const mysqlTexture = useLoader(TextureLoader, "./Textures/skills/mysql.png");
  mysqlTexture.wrapS = THREE.ClampToEdgeWrapping;
  mysqlTexture.wrapT = THREE.ClampToEdgeWrapping;

  const networkTexture = useLoader(
    TextureLoader,
    "./Textures/skills/network.png"
  );
  const nodejsTexture = useLoader(
    TextureLoader,
    "./Textures/skills/nodejs.png"
  );
  const pythonTexture = useLoader(
    TextureLoader,
    "./Textures/skills/python.jpg"
  );
  const reactTexture = useLoader(TextureLoader, "./Textures/skills/react.png");
  const ThreejsTexture = useLoader(
    TextureLoader,
    "./Textures/skills/Threejs.png"
  );

  cupboardtexture.wrapS = cupboardtexture.wrapT = THREE.RepeatWrapping;
  cupboardtexture.repeat.set(4, 4);
  cupboardtexture.rotation = Math.PI / 2;
  cupboardtexture.center.set(0.5, 0.5);
  //rooftexture
  const rooftexture = useLoader(TextureLoader, "./Textures/roof.jpg");
  rooftexture.wrapS = rooftexture.wrapT = THREE.RepeatWrapping;
  rooftexture.repeat.set(4, 4);
  rooftexture.rotation = Math.PI / 2;
  rooftexture.center.set(1, 1);
  //groundtexture
  //rooftexture
  const walltexture = useLoader(TextureLoader, "./Textures/wall.jpg");
  walltexture.wrapS = walltexture.wrapT = THREE.RepeatWrapping;
  walltexture.repeat.set(4, 4);
  walltexture.rotation = Math.PI / 1;
  walltexture.center.set(1, 1);
  //groundtexture
  //flootmattexture
  const flootmattexture = useLoader(TextureLoader, "./Textures/flootmat.jpg");
  flootmattexture.wrapS = flootmattexture.wrapT = THREE.RepeatWrapping;
  flootmattexture.repeat.set(5, 5);
  // wallpaper
  const wallpapertexture = useLoader(TextureLoader, "./Textures/wallpaper.jpg");
  wallpapertexture.wrapS = wallpapertexture.wrapT = THREE.RepeatWrapping;
  wallpapertexture.repeat.set(1, 1);
  wallpapertexture.center.set(1, 1);

  //groundtexture
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.atic_chair.geometry}
        material={nodes.atic_chair.material}
        position={[-2.855, 3.428, -1.102]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={rooftexture} />
      </mesh>
      <mesh
        geometry={nodes.bed.geometry}
        material={nodes.bed.material}
        position={[-1.421, 2.863, -5.701]}
      >
        <meshStandardMaterial map={rooftexture} />
      </mesh>
      <mesh
        geometry={nodes.bedsheets.geometry}
        material={nodes.bedsheets.material}
        position={[-1.72, 3.341, -5.786]}
      >
        <meshStandardMaterial map={flootmattexture} />
      </mesh>
      <mesh
        geometry={nodes.BezierCurve.geometry}
        position={[-0.659, 4.979, -4.659]}
        scale={0.901}
      >
        <meshStandardMaterial
          color="#aaaaaa"
          metalness={1}
          roughness={0.2}
          envMapIntensity={1}
        />
      </mesh>

      <group position={[-2.826, 0.802, -4.451]} scale={[0.543, 0.46, 0.052]}>
        <mesh
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
        >
          <meshBasicMaterial
            color="#4b2e2e" // brick red
            roughness={8} // rough surface
            metalness={0}
          />
        </mesh>
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={nodes.Cube014_1.material}
        >
          <meshBasicMaterial map={chimneytexture} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.computer_table.geometry}
        material={nodes.computer_table.material}
        position={[-3.676, 3.37, -1.259]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshStandardMaterial map={rooftexture} />
      </mesh>
      <group position={[-3.147, 0.484, -1.856]} rotation={[0, 0.323, 0]}>
        <mesh
          geometry={nodes.Plane012.geometry}
          material={nodes.Plane012.material}
        >
          <meshStandardMaterial map={sofatexture} />
        </mesh>
        <mesh
          geometry={nodes.Plane012_1.geometry}
          material={nodes.Plane012_1.material}
        >
          <meshStandardMaterial map={sofatexture} />
        </mesh>
      </group>
      {/* <mesh
      //remove it
        geometry={nodes.frame.geometry}
        material={nodes.frame.material}
        position={[5.556, -12.051, 1.473]}
        rotation={[0, 0, -1.509]}
        scale={1.231}
        
      /> */}
      <group position={[-2.411, -0.001, -3.529]} scale={[2.27, 2.27, 3.446]}>
        <mesh
          geometry={nodes.Plane002.geometry}
          material={nodes.Plane002.material}
        >
          /* house floor */
          <meshStandardMaterial map={walltexture} />
        </mesh>
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={nodes.Plane002_1.material}
        >
          <meshStandardMaterial map={walltexture} />
        </mesh>
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={nodes.Plane002_2.material}
        >
          <meshStandardMaterial map={walltexture} />
        </mesh>
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={nodes.Plane002_3.material}
        >
          <meshStandardMaterial color="#3d3120" />
        </mesh>
        <mesh
          geometry={nodes.Plane002_4.geometry}
          material={nodes.Plane002_4.material}
        >
          <meshBasicMaterial map={wallpapertexture} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.mat.geometry}
        material={nodes.mat.material}
        position={[-3.04, 2.701, -1.176]}
        scale={[0.414, 0.682, 0.682]}
      >
        <meshStandardMaterial map={flootmattexture} />
      </mesh>
      <mesh
        geometry={nodes.matress.geometry}
        material={nodes.matress.material}
        position={[-1.425, 2.984, -5.696]}
      />
      <group
        position={[-0.278, 3.888, -5.662]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.23, 0.536, 0.353]}
      >
        <mesh
          geometry={nodes.Plane034.geometry}
          material={nodes.Plane034.material}
        >
          <meshBasicMaterial color={"#8B5A2B"} />
        </mesh>
        <mesh
          geometry={nodes.Plane034_1.geometry}
          material={nodes.Plane034_1.material}
        />
      </group>
      <mesh
        geometry={nodes.mirror2.geometry}
        material={nodes.mirror2.material}
        position={[-2.131, 4.974, -6.995]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.422, 0.422, 0.265]}
      >
        <meshBasicMaterial color={"#8B5A2B"} />
      </mesh>
      <group position={[-3.789, 3.346, -1.165]} scale={0.199}>
        <mesh
          geometry={nodes.Plane029.geometry}
          material={nodes.Plane029.material}
        >
          <meshStandardMaterial
            color={"#8b7d6b"}
            roughness={0.8}
            metalness={0.1}
          />
        </mesh>
        <mesh
          geometry={nodes.Plane029_1.geometry}
          material={nodes.Plane029_1.material}
        />
      </group>
      <mesh
        geometry={nodes.pillow.geometry}
        material={nodes.pillow.material}
        position={[-0.465, 3.221, -5.679]}
      >
        <meshStandardMaterial map={flootmattexture} />
      </mesh>
      <group position={[-2.425, 0.146, 0.96]}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={nodes.Cube001_1.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
      </group>
      <group position={[-4.29, 0.126, -7.525]}>
        <mesh
          geometry={nodes.Cube027.geometry}
          material={nodes.Cube027.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
        //back steps
        <mesh
          geometry={nodes.Cube027_1.geometry}
          material={nodes.Cube027_1.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.rocking_chair.geometry}
        material={nodes.rocking_chair.material}
        position={[-2.769, 0.661, -3.555]}
        rotation={[0, -0.753, 0]}
      >
        <meshBasicMaterial map={rooftexture} />
      </mesh>
      <mesh
        geometry={nodes.roof.geometry}
        position={[-2.411, 0.055, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial map={rooftexture} />
      </mesh>

      <mesh
        geometry={nodes.roug.geometry}
        material={nodes.roug.material}
        position={[-1.884, 0.357, -2.262]}
      >
        <meshStandardMaterial map={flootmattexture} />
      </mesh>
      <group position={[-4.813, 1.3, -3.278]} scale={[0.556, 1, 1.608]}>
        <mesh
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
        <mesh
          geometry={nodes.Cube006_1.geometry}
          material={nodes.Cube006_1.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
        <mesh
          geometry={nodes.Cube006_2.geometry}
          material={nodes.Cube006_2.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
        <mesh
          geometry={nodes.Cube006_3.geometry}
          material={nodes.Cube006_3.material}
        >
          <meshStandardMaterial map={rooftexture} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.trophy.geometry}
        material={nodes.trophy.material}
        position={[-2.515, 1.306, -4.39]}
        rotation={[0.005, -0.121, 0.038]}
      >
        <meshStandardMaterial
          color="#FFD700" // Gold color
          metalness={1} // Fully metallic
          roughness={0.2} // Slightly shiny surface
        />
      </mesh>
      <group
        position={[-0.239, 0.833, -2.077]}
        rotation={[-Math.PI, 0.087, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
        >
          <meshPhysicalMaterial
            color="#111111"
            roughness={0.6}
            metalness={0.05}
            reflectivity={0.2}
            clearcoat={0.1}
          />
        </mesh>
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={nodes.Cube005_1.material}
        >
          //Tv
          <meshPhysicalMaterial
            color="#135131"
            roughness={0.6}
            metalness={0.05}
            reflectivity={0.2}
            clearcoat={0.1}
          />
        </mesh>
      </group>
      <group position={[-1.845, 1.447, -4.533]}>
        //down wall
        <mesh
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
        >
          <meshStandardMaterial map={wallpapertexture} />
        </mesh>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={nodes.Cube010_1.material}
        >
          <meshStandardMaterial map={wallpapertexture} />
        </mesh>
      </group>
      <group position={[-1.718, 3.729, -2.719]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Plane031.geometry}
          material={nodes.Plane031.material}
        >
          //top wall
          <meshStandardMaterial map={wallpapertexture} />
        </mesh>
        <mesh
          geometry={nodes.Plane031_1.geometry}
          material={nodes.Plane031_1.material}
        >
          <meshStandardMaterial map={wallpapertexture} />
        </mesh>
      </group>
      <mesh
        geometry={nodes.windmill.geometry}
        position={[-5.44, -0.54, -21.085]}
      >
        <meshStandardMaterial color="#3d3120" />
      </mesh>
      <mesh geometry={nodes.ground.geometry} scale={28.338}>
        <meshStandardMaterial map={groundtexture} />
      </mesh>

      <mesh
        geometry={nodes.windmillLeaf.geometry}
        position={[-5.451, 11.01, -19.27]}
      >
        <meshStandardMaterial map={groundtexture} />
      </mesh>
      <mesh
        geometry={nodes.pcScreen.geometry}
        material={nodes.pcScreen.material}
        position={[-3.789, 3.346, -1.165]}
        scale={0.199}
      >

        <meshBasicMaterial map={wallpapertexture}/>
      </mesh>
      <mesh
        geometry={nodes.mirror1Scene.geometry}
        material={nodes.mirror1Scene.material}
        position={[-0.278, 3.888, -5.662]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.23, 1.536, 0.353]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={couragetexture} />
      </mesh>
      <mesh
        geometry={nodes.mirror2Scene.geometry}
        material={nodes.mirror2Scene.material}
        position={[-2.131, 4.974, -6.995]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.422, 0.422, 0.265]}
      />
      <mesh
        geometry={nodes.tvScreen.geometry}
        material={nodes.tvScreen.material}
        position={[-0.239, 0.833, -2.077]}
        rotation={[-Math.PI, 0.087, -Math.PI]}
      >
        <meshStandardMaterial color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.window.geometry}
        material={nodes.window.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#755a32" />
      </mesh>
      <mesh
        geometry={nodes.window2.geometry}
        material={nodes.window2.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#755a32" />
      </mesh>
      <mesh
        geometry={nodes.window3.geometry}
        material={nodes.window3.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#755a32" />
      </mesh>
      <mesh
        geometry={nodes.window4.geometry}
        material={nodes.window4.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#755a32" />
      </mesh>
      <mesh
        geometry={nodes.window5.geometry}
        material={nodes.window5.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#755a32" />
      </mesh>
      <mesh
        geometry={nodes.mirror3.geometry}
        material={nodes.mirror3.material}
        position={[-2.131, 4.23, -4.469]}
        rotation={[Math.PI / 2, 0, 3.136]}
        scale={[0.422, 0.422, 0.265]}
      >
        <meshBasicMaterial color={"#8B5A2B"} />
      </mesh>
      <mesh
        geometry={nodes.mirror3Scene.geometry}
        material={nodes.mirror3Scene.material}
        position={[-2.131, 4.23, -4.469]}
        rotation={[Math.PI / 2, 0, 3.136]}
        scale={[0.422, 0.422, 0.265]}
      />
      <mesh
        geometry={nodes.mirror4.geometry}
        material={nodes.mirror4.material}
        position={[-2.131, 4.468, -0.069]}
        rotation={[Math.PI / 2, 0, 3.136]}
        scale={[0.422, 0.422, 0.265]}
      >
        <meshBasicMaterial color={"#8B5A2B"} />
      </mesh>
      <mesh
        geometry={nodes.mirror4Scene.geometry}
        material={nodes.mirror4Scene.material}
        position={[-2.131, 4.468, -0.069]}
        rotation={[Math.PI / 2, 0, 3.136]}
        scale={[0.422, 0.422, 0.265]}
      />
      <mesh
        geometry={nodes.trophy001.geometry}
        material={nodes.trophy001.material}
        position={[-2.942, 1.306, -4.39]}
        rotation={[0.005, -0.121, 0.038]}
      >
        <meshStandardMaterial
          color="#FFD700" // Gold color
          metalness={1} // Fully metallic
          roughness={0.2} // Slightly shiny surface
        />
      </mesh>
      <mesh
        geometry={nodes.shelfDoorRight.geometry}
        material={nodes.shelfDoorRight.material}
        position={[-2.393, 4.103, -6.612]}
        rotation={[0, 2, 0]}
      >
        <meshStandardMaterial map={cupboardtexture} />
      </mesh>
      <mesh
        geometry={nodes.shelfBody.geometry}
        material={nodes.shelfBody.material}
        position={[-2.388, 4.112, -6.787]}
      >
        <meshStandardMaterial map={cupboardtexture} />
      </mesh>
      <mesh
        geometry={nodes.shelfDoorLeft.geometry}
        material={nodes.shelfDoorLeft.material}
        position={[-3.148, 4.112, -6.612]}
        rotation={[0, -2, 0]} //x,777,x
      >
        <meshStandardMaterial map={cupboardtexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame1.geometry}
        material={nodes.pictureFrame1.material}
        position={[-3.032, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene1.geometry}
        material={nodes.pictureScene1.material}
        position={[-3.032, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={flutterTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame2.geometry}
        material={nodes.pictureFrame2.material}
        position={[-2.846, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>

      <mesh
        geometry={nodes.pictureScene2.geometry}
        position={[-2.846, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 1.04]}
        // scale={[7, 1, 4]}
      >
        <planeGeometry args={[0.218, 0.354, 2.5]} />
        <meshBasicMaterial map={reactTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame4.geometry}
        material={nodes.pictureFrame4.material}
        position={[-2.665, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame3.geometry}
        material={nodes.pictureFrame3.material}
        position={[-2.49, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene3.geometry}
        material={nodes.pictureScene3.material}
        position={[-2.665, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={ThreejsTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene4.geometry}
        material={nodes.pictureScene4.material}
        position={[-2.49, 4.305, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={figmaTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame8.geometry}
        material={nodes.pictureFrame8.material}
        position={[-3.032, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame7.geometry}
        material={nodes.pictureFrame7.material}
        position={[-2.846, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame6.geometry}
        material={nodes.pictureFrame6.material}
        position={[-2.49, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame5.geometry}
        material={nodes.pictureFrame5.material}
        position={[-2.665, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene8.geometry}
        material={nodes.pictureScene8.material}
        position={[-3.032, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={blenderTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene7.geometry}
        material={nodes.pictureScene7.material}
        position={[-2.846, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={javaTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene6.geometry}
        material={nodes.pictureScene6.material}
        position={[-2.49, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={javascriptTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene5.geometry}
        material={nodes.pictureScene5.material}
        position={[-2.665, 4.117, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={pythonTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame12.geometry}
        material={nodes.pictureFrame12.material}
        position={[-2.665, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame11.geometry}
        material={nodes.pictureFrame11.material}
        position={[-2.49, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame10.geometry}
        material={nodes.pictureFrame10.material}
        position={[-2.846, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureFrame9.geometry}
        material={nodes.pictureFrame9.material}
        position={[-3.032, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <meshBasicMaterial color={"#FFD700"} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene12.geometry}
        material={nodes.pictureScene12.material}
        position={[-2.665, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={networkTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene11.geometry}
        material={nodes.pictureScene11.material}
        position={[-2.49, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={nodejsTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene10.geometry}
        material={nodes.pictureScene10.material}
        position={[-2.846, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={linuxTexture} />
      </mesh>
      <mesh
        geometry={nodes.pictureScene9.geometry}
        material={nodes.pictureScene9.material}
        position={[-3.032, 3.903, -6.764]}
        rotation={[-0.288, 0, 0]}
        scale={[0.418, 0.354, 0.04]}
      >
        <planeGeometry args={[0.28, 0.384, 2.5]} />
        <meshBasicMaterial map={mysqlTexture} />
      </mesh>
      <mesh
        geometry={nodes.frontDoor.geometry}
        material={nodes.frontDoor.material}
        position={[-3.051, 1.155, -0.123]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#2a9f7c" />
      </mesh>

      <group position={[-0.671, 1.131, -4.533]}>
        <mesh
          geometry={nodes.Cube013.geometry}
          material={nodes.Cube013.material}
        >
          <meshStandardMaterial color="#2a9f7c" />
        </mesh>
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={nodes.Cube013_1.material}
        >
          <meshStandardMaterial color="#2a9f7c" />
        </mesh>
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={nodes.Cube013_2.material}
        >
          <meshStandardMaterial color="#2a9f7c" />
        </mesh>
      </group>
      <mesh
        geometry={nodes.bedroomDoor.geometry}
        material={nodes.bedroomDoor.material}
        position={[-2.835, 3.598, -4.444]}
        rotation={[Math.PI / 2, 0, 0.446]}
      >
        <meshStandardMaterial color="#2a9f7c" />
      </mesh>
      <group position={[-2.411, -0.001, -3.529]} scale={[2.27, 2.27, 3.446]}>
        <mesh
          geometry={nodes.Plane022.geometry}
          material={nodes.Plane022.material}
        >
          <meshStandardMaterial color="#2a9f7c" />
        </mesh>
        <mesh
          geometry={nodes.Plane022_1.geometry}
          material={nodes.Plane022_1.material}
        >
          <meshStandardMaterial color="#2a9f7c" />
        </mesh>
      </group>
      <mesh
        geometry={nodes.frontDoorFrame.geometry}
        material={nodes.frontDoorFrame.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#2a9f7c" />
      </mesh>
      <mesh
        geometry={nodes.kitchenDoorFrame.geometry}
        material={nodes.kitchenDoorFrame.material}
        position={[-1.845, 1.447, -4.533]}
      >
        <meshStandardMaterial color="#2a9f7c" />
      </mesh>
      <mesh
        geometry={nodes.backDoorFrame.geometry}
        material={nodes.backDoorFrame.material}
        position={[-2.411, -0.001, -3.529]}
        scale={[2.27, 2.27, 3.446]}
      >
        <meshStandardMaterial color="#2a9f7c" />
      </mesh>
      <mesh
        geometry={nodes.bedroomDoorFrame.geometry}
        material={nodes.bedroomDoorFrame.material}
        position={[-1.718, 3.729, -2.719]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial color="#2a9f7c" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/courageHouse.glb");
